import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ParentNav from "@/defaults/home-nav/ParentNav";
import ParentFooter from "@/defaults/home-footer/ParentFooter";
import AosWrapper from "@/defaults/aos-wrapper/AosWrapper";
import NextTopLoader from "nextjs-toploader";
import Context from "@/defaults/context/Context";
import ThemeProvider from "@/components/theme-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AosWrapper>
            <NextTopLoader
              color="#FFFF00"
              showSpinner={true}
              height={3}
              zIndex={99999999999}
            />
            <Context>
              <Toaster className="z-[999999]" />
              <ParentNav />
              {children}
              <ParentFooter />
            </Context>
          </AosWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
